%YAML 1.2
---
db:
  jdbc:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn?currentSchema=movieland
    username: postgres
    password: root
    initialSize: 4
    maxTotal: 8

movie:
  randomCount: 3

genre:
  cacheUpdatePeriod: 14400000 # 4 * 60 * 60 * 1000 = 4 hours

logger:
  fileName: movieland
  logLevelFile: DEBUG
  logLevelConsole: DEBUG